### ISSUE TITLE
Error on Deploy FlashMintDemo.sol

### ISSUE THREAD

**Issue by andermarce** [fifikobayashi/FlashMintArbitrage#1]
browser/FlashMintDemo.sol:66:9: Warning: Unused local variable. uint256 DAIBought = executeSwapOnKyber(ETH_TOKEN_ADDRESS, srcQty, daiToken, platformWallet, maxDestAmount); ^---------------^

**Comment by fifikobayashi** [comment]
That's just a warning which shouldn't stop the contract from compiling. If it's not compiling then it's caused by an issue not listed above.

To get rid of that warning just don't set it to a DAIBought variable, i.e. just delete the "uint 256 DAIBought =" part of that line. I originally intended to do a few extra steps of self liquidation using that DAI but never got around to it. Not setting it to DAIBought won't break anything.
